name: docker_build
on: [push]

env:
  HOST_NAME: asia.gcr.io
  APP_NAME: hello-app
  APP_VERSION: v5

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set gcloud config
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      - name: Configure docker to use the gcloud cli
        run: gcloud auth configure-docker --quiet
      - name: Build a docker image
        run: docker build -t ${HOST_NAME}/${{ secrets.GCP_PROJECT_ID }}/${APP_NAME}:${APP_VERSION} .
      - name: Push the docker image
        run: docker push ${HOST_NAME}/${{ secrets.GCP_PROJECT_ID }}/${APP_NAME}:${APP_VERSION}
