name: docker_build
on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      PROJECT: tmtest-k8s
      HOSTNAME: asia.gcr.io
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - run: gcloud config set project ${PROJECT}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${PROJECT}
          service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      - name: Configure docker to use the gcloud cli
        run: gcloud auth configure-docker --quiet
      - name: Build a docker image
        run: docker build -t asia.gcr.io/${PROJECT}/hello-app:v2 .
      - name: Push the docker image
        run: docker push asia.gcr.io/${PROJECT}/hello-app:v2
