name: docker_build
on: [push]

env:
  PROJECT: tmtest-k8s
  HOSTNAME: asia.gcr.io
  REGION: asia-northeast1

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - run: |
          gcloud config set project tmtest-k8s
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: tmtest-k8s
          service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      - name: Configure docker to use the gcloud cli
        run: gcloud auth configure-docker --quiet
      - name: Build a docker image
        run: docker build -t asia.gcr.io/tmtest-k8s/hello-app:v1 .
      - name: Push the docker image
        run: docker push asia.gcr.io/tmtest-k8s/hello-app:v1
